### PR TITLE
Add options to specify heap settings for agent and server

### PR DESCRIPTION
**Pull request by vladistan**
While trying to troubleshoot [this issue](https://github.com/gocd/gocd/issues/1202) I found that default Go memory options for JVM are not always ideal.

Here is the patch that allows to configure memory options for agent and server

### CODE REVIEW

**Comment by jmkeyes** [comment]
Thanks for the patch!

Those are fairly generous defaults for the JVM heap size -- initially 512MB up to a maximum of 1024MB. The currently documented [system requirements](https://docs.go.cd/current/installation/system_requirements.html) indicate a minimum physical memory requirement of 1GB for a server and 128MB for an agent.

I'd prefer to make both parameters optional (`undef` by default) and have them conditionally added to `go-(server|agent).default.erb` when provided. This would also give Puppet an opportunity to validate the values provided during catalog compilation.

Additionally, it might be beneficial to prefix the parameters with `jvm_` to explicitly indicate the parameters are for tuning the JVM and not for some other purpose.

What do you think?

**Comment by vladistan** [comment]
128MB for an agent is really low.   Although depends on what kind of jobs you are running.  Looks like the memory usage depends on number of unit tests in the job or more specifically number size of test result artifacts.  

 The defaults are actually come from go-agent.sh and go-server.sh scripts installed by RPM.   ( 16.9 )   I had agent OOM crashes all the time until I switched to 1G / 4G.   This is mostly for my Apache PIG jobs that run for 10 hours and produce tons of tests.   I think for normal person 512/1G is fine.   

As for having those undef.  I am all for it, but I never done this when erb templates are involved.  It would take me some time to research and put in code.  Especially now I don't have a spare cluster anymore to experiment with.   I did this patch on the sick cluster over the weekend, and it is now back in production.     Feel free to put these changes in,  the earliest I can work on this again is probably in three weeks or so.

**Comment by jmkeyes** [comment]
I've added a few commits. WIll those changes work for you?

**Comment by vladistan** [comment]
Yes looks good

**Comment by jmkeyes** [comment]
Changes merged; I've released a new version of the module on the Forge.

**Pull request merged**
